apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: consulta-saldo
  name: consulta-saldo
spec:
  replicas: 1
  selector:
    app: consulta-saldo
    deploymentconfig: consulta-saldo
  template:
    metadata:
      labels:
        app: consulta-saldo
        deploymentconfig: consulta-saldo
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: consulta-saldo
          image: docker-registry.default.svc:5000/prueba-service-mesh/consulta-saldo:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"undertow":{"io-threads":10, "worker-threads":20 }}}'
            - name: JAVA_OPTIONS
              value: '-Xms640m -Xmx1024m -Dfile.encoding=ISO-8859-1'
          envFrom:
            - configMapRef:
                name: configmap-consulta-saldo
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
              scheme: HTTP
            failureThreshold: 2
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          resources:
            limits:
              cpu: 400m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 640Mi
